CREATE TABLE [dbo].[Sales]
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	BookId INT NOT NULL,
	Count INT NOT NULL,
	Date DATETIME NOT NULL,
	Cost MONEY NOT NULL,
	CONSTRAINT FK_Sales_To_Book FOREIGN KEY (BookId) REFERENCES [Book](Id),
	CONSTRAINT CK_Count CHECK (Count > 0)
 )